### ISSUE TITLE
cython requirement warning

### ISSUE THREAD

**Issue by JohannesBuchner** [JohannesBuchner/UltraNest#26]
In setup.py, when the `from Cython.Build import cythonize` import fails, we should display a nice error message to the user, saying "please install cython first".

**Comment by MuellerSeb** [comment]
Was just clicking through this package, because of the little conda encounter we had because of our common pypy problem... and this issue here looks familiar!
I am maintaining a package using cython extensions myself and I solved this exact problem by using the new `pyproject.toml`:
https://github.com/GeoStat-Framework/GSTools/blob/develop/pyproject.toml

This is used to rely on pep517/518 builds for wheels and sdist and creates a separate build environment when building from source. Since the deps are defined in a toml file, one can prevent the problem of having dependencies in the `setup.py`, that can't be required in there as build dependency.

Just have a look at GSTools that I linked above. I reworked the whole building/installing infrastructure the be future-proof with cython extensions (https://github.com/GeoStat-Framework/GSTools/pull/154).
Also have a look at the new package https://github.com/scipy/oldest-supported-numpy to get the correct numpy version build your cython extensions (https://github.com/GeoStat-Framework/GSTools/pull/165).

This was also very helpful: https://scikit-hep.org/developer/packaging

Beside that: Your package looks quite interesting. Will have a second look in the future I guess ;-)
Cheers, Sebastian

**Comment by JohannesBuchner** [comment]
I think this is solved.
