### ISSUE TITLE
Convergence from MWW test

### ISSUE THREAD

**Issue by gretaguidi** [JohannesBuchner/UltraNest#30]
* UltraNest version: 3.2.0
* Python version: 3.6.8
* Operating System: MacOS 10.13

This is more of a general question rather than a technical issue.
In the ordertest module, a routine performing a Mann-Whitney-Wilcoxon test is implemented (in the ultranest 3.2.0 version a MWW test is performed by default at the end of each run, and the result is store in the result.json file). In many cases I get a negative outcome (converged = False) even if the fit looks good (e.g. criteria on logZerr and dK satisfied, gaussian-like posterior distributions). Question: how much weight should I give to the outcome of this test? Can I consider my fit formally converged even if this condition is not satisfied? And if not, how can I "improve" my fit to get a convergence for the MWW test, e.g. increase the number of samples, decrease the logZerr threshold ?

Thanks a lot.

**Comment by JohannesBuchner** [comment]
Yes, I see this a lot as well. I would not give much weight to this.

Currently, the test statistic is accumulated until the z-score reaches 2 sigma. The number of iterations (run length) is recorded, and the test statistic reset. [here in the code](https://github.com/JohannesBuchner/UltraNest/blob/master/ultranest/netiter.py#L769)

If there are no runs recorded (it never reached the threshold), it prints out "converged: True".

But this is inappropriately conservative, because by chance one would expect a 2 sigma z-score after a while. This is inversely related to a p-hacking phenomenon -- if one keeps testing after every accumulated new data point, the result is different than when testing only after a pre-defined number of data points.

In the [original paper](https://arxiv.org/abs/2006.03371), IIRC they made chunks, and evaluated the z-score/p-value in those. Perhaps there is a reasonable chunk size based on some multiple of the number of live points (but what to do when nlive varies or is very small, <50?). I was unsure how to choose the chunk size, so I went for accumulating run lengths here.

Suggestions are welcome.

In any case, the code must be updated to correct for the number of tests made.

If the run lengths are used, we should simulate how many runs are expected given N iterations and the z-score threshold. Then the insertion_order_converged function could check the convergence better.

If you have time, a simple exercise would be to:
* create a UniformOrderAccumulator (from ultranest.ordertest) object,
* iteratively:
  * call the .add(r, N) function with a random integer from 0 to N inclusively), 
  * look at the .zscore, if its absolute is > 2, record the length, and .reset()

This should give us the expected distribution of the number of runs, given a number of iterations (e.g., 100,000).
Then we'd have to figure out how significant an observed number of runs is, given the number of nested sampling iterations.

My understanding is that the answer would be trivial if the z-scores were independent in each iteration, but they are not, they are highly correlated. The answer for chunks is easier, because there the p-values are independent.

**Comment by gretaguidi** [comment]
Now it's much clearer, thank you very much. So I see that at the moment the output of  insertion_order_converged does not give a good indication on whether the run has passed the MWW test.

If I understand correctly what you suggested, to test the number of runs that give a zscore>2 sigma from a uniform distribution and N =100000 iterations, I would do something like:

```
N = 100000
length = [[] for _ in range(100)]
for i in range(100):
	acc = ultranest.ordertest.UniformOrderAccumulator(N)
	r = np.random.randint(low=0, high=N+1, size = N)
	for rr in r:
		acc.add(rr, N)
		if abs(acc.zscore)>2:
			length[i].append(len(acc))
			acc.reset()

```
With the code above I run 100 tests, and I get a median value of 2.0 - mean value of 2.4 - for the number of  recorded run lengths, i.e. on average I get 2 times a zscore >2 for 100.000 iterations. 
Regarding the distribution of the run lengths, I get a median of 70 (mean of 5114), and MAD (median absolute deviation) of 100 - standard deviation of 15600. 

I am not sure how to correlate these value with the measured run lengths in ultranest, given that you mentioned the z-scores are not independent at each iteration.

I don't have any robust suggestion for running the MWW test for a variable number of live points.

**Comment by JohannesBuchner** [comment]
OK, I think 2 is way too low. I extended it to a threshold 4 by default. This seems to give run lengths not shorter than 10^5.5, if I did it correctly. Can you test the latest version?

**Comment by gretaguidi** [comment]
Using the latest version (3.3.1) I run again a few fits for which I had convergence = False for the MWW test. I now get inf iterations (no detected runs) and therefore a positive convergence

I think there is a typo in the code comment [on line 700](https://github.com/JohannesBuchner/UltraNest/blob/1a06f88dc19d80e76a692a26f1fe573c8e55dcc5/ultranest/netiter.py#L700) and it should say: 
If the number of runs exceeds the number of iterations divided by 10^5.5, the run is likely 'biased'

**Comment by JohannesBuchner** [comment]
Thanks, I am closing this now.
