### ISSUE TITLE
how could i stop the runing program when i thought the result  achieve my expectations.

### ISSUE THREAD

**Issue by senmaaa** [JohannesBuchner/UltraNest#35]
* UltraNest version: 3.3
* Python version: 3.8
* Operating System: Ubuntu 16.4

### Description

I want to stop the  running program ,for that the results displaying  is achieve my expectation。I hope to stop program and save the result as it was convergence  without running program code again.

### What I Did

![图片](https://user-images.githubusercontent.com/44462000/124874864-d1d2c000-dffa-11eb-9e09-f4b2d264e042.png)

**Comment by JohannesBuchner** [comment]
You can ctrl-c to stop, and points.hdf5 will contain the sampled points so far.

It seems that your likelihood is not flat yet at this point, or perhaps there are numerical issues because the number is so large (1e13) that small changes (+-0.1) cannot be seen. So perhaps you can define your loglikelihood so that the largest values are near zero.
