### ISSUE TITLE
Obtain MAP Estimate

### ISSUE THREAD

**Issue by PBGraff** [JohannesBuchner/UltraNest#6]
* UltraNest version: 2.1.2
* Python version: 3.7
* Operating System: Mac OSX 10.14

### Description

While the documentation is clear about how to obtain the maximum likelihood estimate (MLE), it is not clear about how to obtain the maximum a posteriori (MAP) estimate.

### What I Did

The point resulting from the code below does not seem to correspond to the MAP. My posterior distribution is pretty Gaussian, so I was surprised by how different the two parameter values were.

```python
# MLE
imax1 = np.argmax(sampler.results['weighted_samples']['L'])
v_mle = sampler.results['weighted_samples']['v'][imax1, :]

# MAP?
imax2 = np.argmax(sampler.results['weighted_samples']['w'])
v_map = sampler.results['weighted_samples']['v'][imax2, :]
```

**Comment by JohannesBuchner** [comment]
I think this method does not work because most of the weight is in a shell, and almost no weight is at the maximum likelihood point (because volume is tiny there). So the live point where most weight is will be off the peak.

Not sure I would recommend using the MAP at all, if you already have samples. I would either chose a random point, use the mean, or average what you want to do with the MAP over all points.

**Comment by PBGraff** [comment]
OK, so if I understand correctly, there isn't a single point that can be used as a good MAP estimate. The higher likelihood samples are just more densely populated in a region where each has less individual weight.

**Comment by JohannesBuchner** [comment]
I am closing this issue, but if you have an idea for a feature, please feel free to reopen or open a new issue.
