### ISSUE TITLE
unable to understand ultranest corner plot

### ISSUE THREAD

**Issue by shiningsurya** [JohannesBuchner/UltraNest#68]
* UltraNest version: 3.4.4
* Python version: 3.8
* Operating System: centos 7

### Description

Given some parameters (`3 angles + 1 angular velocity`) as initial parameters, model integrates in time and produces some `(time, measurement)`.
Objective is to given a set of `(time, measurement)`, estimate the initial parameters which fit the data. 

i have simulated a mock dataset `(time, measurement)` using some set of parameters. Evaluating the likelihood on this dataset using that same set of parameters returns zero.

Ultranest explores until `L=-2e4` and produces corner plot like this. 
[corner.pdf](https://github.com/JohannesBuchner/UltraNest/files/9010689/corner.pdf)
The angle parameters have `wrap=True`.
`frac_remain` is set to `1e-9`.

### What i expect

i expect ultranest to go until `L=1e-9`. 
Is there any way to sample more points during high likelihoods?

In a way, i am using ultranest as an optimization tool to find all the parameters which can fit the data. 
This is because the model has a lot of degeneracies. 
Is there a way to get the list of all the high likelihood samples?

Can you please clarify the difference between various types of `chains`? (`equal_weighted_post.txt, weighted_post.txt`)
Also, is there any documentation on how to interpret the `points` and `tree` hdf5?
i could not find what various columns of `points.hdf5` are.

thanks in advance and sorry for the trouble

**Comment by hposborn** [comment]
> Also, is there any documentation on how to interpret the points and tree hdf5?
> i could not find what various columns of points.hdf5 are.

I would also like to echo this request - I cannot figure out what the columns in points.hdf5 refer to. I seem to have 2N+1 columns, where N is the number of parameters, but exactly what each column is and how to use them is not documented anywhere.

**Comment by JohannesBuchner** [comment]
Yes, the output files should be documented better.

* equal_weighted_post.txt: equally weighted posterior samples (similar to a Markov chain)
* weighted_post.txt: posterior samples with a weight attached. This is made by NS directly, and the above is produced from this. However, carrying the weights around is cumbersome.
* points.hdf5: this is sort of an internal file, but the columns are (used here for example https://github.com/JohannesBuchner/UltraNest/blob/master/ultranest/integrator.py#L795): likelihood threshold under which the point was sampled, likelihood of the point, a quality indicator (0 for MLFriends, otherwise the number of steps in the step sampler), u-space (unit cube) coordinates, p-space (transformed parameters) coordinates.

**Comment by JohannesBuchner** [comment]
Regarding the original question: the posterior looks flat, and sampling at higher likelihood (which have a tiny region) will not change this. Look at your loglikelihood function and check why the values are always the same.

Maybe you have a bug in your loglikelihood function which returns similar values. For example, are you sure you are returning the log of a likelihood?

**Comment by JohannesBuchner** [comment]
I am updating the docs, and saw that the output files are briefly documented here: https://johannesbuchner.github.io/UltraNest/performance.html

It's a bit hidden, so I intend to make it more discoverable.

**Comment by JohannesBuchner** [comment]
I think this is fixed with the new docs and latest release. Please try and let me know.
